[package]
name = "rdl"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "2.33.3", features = ["yaml", "color"] }
color-eyre  = "0.5.11"
itertools = "0.10.1"
nsi = "0.6.0"
pest = "2.1.3"
pest_derive = "2.1.0"

[build-dependencies]
clap = { version = "2.33.3", features = ["yaml", "color"] }

[profile.dev]
split-debuginfo = "unpacked"
