[package]
name = "delight-helpers"
version = "0.1.3"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2021"
resolver = "2"
keywords = ["graphics", "rendering", "3d", "ray-tracing", "scene-description"]
categories = ["graphics", "multimedia::images", "rendering"]
license = "Apache-2.0 OR BSD-3-Clause OR MIT OR Zlib"
description = "Command line utilities/helpers for the 3Delight renderer."
exclude = [".github/**/*", "crates/**/*"]
readme = "README.md"
homepage = "https://www.3delight.com/"
documentation = "https://docs.rs/nsi/"
repository = "https://github.com/virtualritz/rdl/"

[[bin]]
name = "rdl"
path = "src/rdl.rs"

[dependencies]
clap = { version = "2.33.3", features = ["yaml", "color"] }
eyre = { version = "0.6.5", default-features = false }
itertools = "0.10.1"
nsi = "0.6.0"
pest = "2.1.3"
pest_derive = "2.1.0"

[build-dependencies]
clap = { version = "2.33.3", features = ["yaml", "color"] }

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
