[package]
name = "delight-helpers"
version = "0.1.5"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2021"
keywords = ["graphics", "rendering", "3d", "ray-tracing", "scene-description"]
categories = ["command-line-utilities", "graphics", "multimedia::images", "rendering"]
license = "Apache-2.0 OR BSD-3-Clause OR MIT OR Zlib"
description = "Command line utilities/helpers for the 3Delight renderer."
exclude = [".github/**/*", "crates/**/*"]
readme = "README.md"
homepage = "https://www.3delight.com/"
documentation = "https://docs.rs/delight-helpers/"
repository = "https://github.com/virtualritz/delight-helpers/"

[[bin]]
name = "rdl"
path = "src/rdl.rs"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2", features = ["derive", "color", "suggestions", "unicode", "wrap_help"] }
clap_complete = "4.2"
fern = { version = "0.6.2", features = ["colored"] }
frame-sequence = "0.1"
human-panic = "1.1"
log = { version = "0.4.17", features = ["std"] }
notify = "5.1.0"
nsi = { version = "0.7", path = "../nsi-old" }
#nsi-traits = { path = "../nsi/crates/nsi-traits" }
#wax = { version = "0.5.0", features = ["diagnostics-report"] }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
